### ISSUE TITLE
110 warnings

### ISSUE THREAD

**Issue by optomao** [xjtupurple/xjtupurple.github.io#10]
![B3586EA2-DD7C-497D-BD04-B1ED180155F4](https://user-images.githubusercontent.com/56309178/104577427-726fa500-5694-11eb-97cb-3376dd0b137c.jpeg)
上图这个开发者已经被搞了……
不知道学校会不会算账。为了保险还是稳一点吧，鉴于现在已经不怎么需要紫码坐校车，优先保护自己吧。

**Comment by endaytrer** [comment]
目前该项目已经不再被部署. 除了要挂的期末, 目前作者暂时平安. 感谢关心!
