### ISSUE TITLE
建议顶部Banner的颜色设为可替换的

### ISSUE THREAD

**Issue by telepathphd** [xjtupurple/xjtupurple.github.io#2]
建议顶部Banner的颜色设为可替换的，目前是比较正的蓝色（1671f0），实际上不同学院的背景色不同，像能动的是紫色（6e49b9），如果能把学院改成选项，然后自动匹配颜色就更棒了。
加油！

**Comment by endaytrer** [comment]
我看到的校园码的源代码里和#1671f0并列的两个颜色是#7547C0 (和你所说的#6e49b9相似) 和#353A73, 它是和本科生, 研究生和留学生(看拼音猜的)对应的. 至于学院改变颜色的选项我目前不是很清楚, 如果你能提供更详细的信息我会万分感谢!
<img width="318" alt="截屏2020-06-2712 44 28" src="https://user-images.githubusercontent.com/49216312/85914782-f3d82500-b873-11ea-9cee-806bdf44269e.png">

**Comment by telepathphd** [comment]
我明白了，应该是我猜错了，我以为我紫色是出于能动的原因。那感觉可以添加一个选择本科、研究和留学生的选项吧！甚至可以再加个绿码的选项
